# Generated by Django 5.1.4 on 2024-12-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill_alter_generalsetting_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
